/* ============================================================================
   The entire tech tree is data (doc §2.1, §4.4). The engine has no idea what a
   greenhouse *is* — it runs these recipes against resource pools. Balancing is
   editing these numbers, never touching the engine.

   consumes/produces/solar are PER SECOND at full operation. priority = power-
   allocation rank; brownout sheds the LOWEST first, so farming starves before
   life support. (Doc §2.4 pass 3, §4.4.)
   ============================================================================ */
import type { BuildingDef } from "@shared/types";

export const DEFS: Record<string, BuildingDef> = {
  hub: {
    id: "hub", name: "Pressure Hub", glyph: "HUB",
    foot: [2, 2], h: 30, color: "#3a4750",
    cost: { power: 0 }, matCost: 0,
    staffing: 0, consumes: { power: 1.5 }, produces: {},
    requiresPressure: false, isHub: true, priority: 99, door: 2,
    caps: { oxygen: 30 },
    desc: "The center of a pressure network. Sealed buildings connect back to a hub, directly or through corridors and other sealed buildings. Each hub starts its own network.",
  },
  corridor: {
    id: "corridor", name: "Corridor", glyph: "===",
    foot: [1, 1], h: 10, color: "#2c363d",
    cost: { power: 0 }, matCost: 2,
    staffing: 0, consumes: { power: 0.2 }, produces: {},
    requiresPressure: false, conduit: true, priority: 95,
    desc: "A pressurized tube that carries the seal between the network and sealed buildings. Sealed buildings lay their own when placed; use this for manual runs and repairs.",
  },
  hab: {
    id: "hab", name: "Habitat", glyph: "HAB",
    foot: [1, 1], h: 22, color: "#39444c",
    cost: { power: 0 }, matCost: 24,
    staffing: 0, consumes: { power: 1.0 }, produces: {},
    requiresPressure: true, priority: 88, popCap: 4, door: 2,
    desc: "Beds for colonists; new ones arrive or are born only into free beds. Connected to the seal, it also shelters the crew from hazards.",
  },
  solar: {
    id: "solar", name: "Solar Array", glyph: "PV",
    foot: [2, 2], h: 8, color: "#1d2730",
    cost: { power: 0 }, matCost: 16,
    staffing: 0, consumes: {}, produces: {}, solar: 22,
    requiresPressure: false, priority: 0,
    desc: "Power from sunlight: most at noon, none at night, little in a dust storm.",
  },
  battery: {
    id: "battery", name: "Battery Bank", glyph: "BAT",
    foot: [1, 1], h: 14, color: "#222d34",
    cost: { power: 0 }, matCost: 14,
    staffing: 0, consumes: {}, produces: {},
    requiresPressure: false, priority: 0, caps: { power: 120 },
    desc: "Stores power for the night and for storms.",
  },
  extractor: {
    id: "extractor", name: "Ice Extractor", glyph: "H2O",
    foot: [1, 1], h: 18, color: "#33403a",
    cost: { power: 0 }, matCost: 18,
    staffing: 1, consumes: { power: 5 }, produces: { water: 4 },
    requiresPressure: false, priority: 45,
    desc: "Makes water from the ground with power alone. Needs one colonist; a miner makes more.",
  },
  awg: {
    id: "awg", name: "Atmospheric Water Generator", glyph: "AWG",
    foot: [1, 1], h: 22, color: "#2c4048",
    cost: { power: 0 }, matCost: 45,
    staffing: 1, consumes: { power: 12 }, produces: { water: 8 },
    requiresPressure: false, priority: 44,
    desc: "Pulls water out of the air: more water than the extractor, for more power. Needs one colonist.",
  },
  aquifer: {
    id: "aquifer", name: "Aquifer Well", glyph: "AQF",
    foot: [1, 1], h: 18, color: "#27485a",
    cost: { power: 0 }, matCost: 60,
    staffing: 1, consumes: { power: 3 }, produces: { water: 14 }, needsAquifer: true,
    requiresPressure: false, priority: 46,
    desc: "Pumps an underground aquifer: the most water for the least power. Must sit on an aquifer site. Needs one colonist.",
  },
  reclaimer: {
    id: "reclaimer", name: "Water Reclaimer", glyph: "RCL",
    foot: [1, 1], h: 18, color: "#34464a",
    cost: { power: 0 }, matCost: 40,
    staffing: 1, consumes: { power: 6 }, produces: {}, reclaim: { frac: 0.45, max: 2.5 },
    requiresPressure: true, priority: 40, door: 2,
    desc: "Recycles used water, returning part of what the colony uses. Needs one colonist and the seal.",
  },
  electrolysis: {
    id: "electrolysis", name: "Electrolysis Unit", glyph: "O2",
    foot: [1, 1], h: 20, color: "#2f3a44",
    cost: { power: 0 }, matCost: 22,
    staffing: 1, consumes: { power: 7, water: 2.5 }, produces: { oxygen: 5 },
    requiresPressure: true, priority: 82, door: 2,
    desc: "Splits water into oxygen for the crew to breathe. Needs one colonist (an engineer makes more) and the seal. Among the last to lose power in a brownout.",
  },
  greenhouse: {
    id: "greenhouse", name: "Hydroponics", glyph: "GRO",
    foot: [2, 2], h: 16, color: "#33422f",
    cost: { power: 0 }, matCost: 30,
    staffing: 1, consumes: { power: 6, water: 3 }, produces: { food: 5, oxygen: 0.4 },
    requiresPressure: true, priority: 30, door: 2,
    desc: "Grows food, with a little oxygen on the side. Needs one colonist (a botanist grows more) and the seal. Loses power early in a brownout.",
  },
  medbay: {
    id: "medbay", name: "Med-Bay", glyph: "MED",
    foot: [1, 1], h: 18, color: "#46333b",
    cost: { power: 0 }, matCost: 26,
    staffing: 1, consumes: { power: 4 }, produces: {},
    requiresPressure: true, priority: 60, door: 2,
    desc: "Heals injured colonists, fastest at its door. Needs one colonist (a medic heals faster) and the seal.",
  },
  cistern: {
    id: "cistern", name: "Water Cistern", glyph: "CIS",
    foot: [1, 1], h: 16, color: "#2a3a40",
    cost: { power: 0 }, matCost: 16,
    staffing: 0, consumes: {}, produces: {},
    requiresPressure: false, priority: 0, caps: { water: 160 },
    desc: "Stores water.",
  },
  o2tank: {
    id: "o2tank", name: "Oxygen Tank", glyph: "TNK",
    foot: [1, 1], h: 18, color: "#28363f",
    cost: { power: 0 }, matCost: 18,
    staffing: 0, consumes: {}, produces: {},
    requiresPressure: false, priority: 0, caps: { oxygen: 130 },
    desc: "Stores oxygen.",
  },
  deflector: {
    id: "deflector", name: "Deflector Array", glyph: "DFL",
    foot: [1, 1], h: 20, color: "#3a2c44",
    cost: { power: 0 }, matCost: 30,
    staffing: 0, consumes: { power: 3.5 }, produces: {},
    requiresPressure: false, priority: 35,
    desc: "While powered, each deflector turns back half of the UFO's abduction attempts; two turn back three in four. Loses power early in a brownout.",
  },
  windturbine: {
    id: "windturbine", name: "Wind Turbine", glyph: "WND",
    foot: [1, 1], h: 26, color: "#2e3d49",
    cost: { power: 0 }, matCost: 28,
    staffing: 0, consumes: {}, produces: {}, wind: 9,
    requiresPressure: false, priority: 0,
    desc: "Power from wind: strongest at night and in dust storms, when solar is weakest.",
  },
  geothermal: {
    id: "geothermal", name: "Geothermal Tap", glyph: "GEO",
    foot: [1, 1], h: 16, color: "#453428",
    cost: { power: 0 }, matCost: 45,
    staffing: 0, consumes: {}, produces: {}, steady: 6, needsVent: true,
    requiresPressure: false, priority: 0,
    desc: "Steady power, day and night. Must sit on a vent.",
  },
  reactor: {
    id: "reactor", name: "Fission Reactor", glyph: "FIS",
    foot: [2, 2], h: 26, color: "#414433",
    cost: { power: 0 }, matCost: 120,
    staffing: 1, consumes: { water: 0.5 }, produces: { power: 20 },
    requiresPressure: false, priority: 0,
    desc: "Large, steady power from a little water. Needs one colonist; an engineer makes more.",
  },
  printer: {
    id: "printer", name: "3D Printer", glyph: "3DP",
    foot: [1, 1], h: 18, color: "#3f3347",
    cost: { power: 0 }, matCost: 40,
    staffing: 0, consumes: { power: 6 }, produces: {}, producesMat: 0.35,
    requiresPressure: false, priority: 15,
    desc: "Turns regolith into building materials using power. No crew.",
  },
  bioprinter: {
    id: "bioprinter", name: "Bio Printer", glyph: "BIO",
    foot: [1, 1], h: 18, color: "#3d4a3a",
    cost: { power: 0 }, matCost: 35,
    staffing: 0, consumes: { power: 8, water: 2 }, produces: { food: 3 },
    requiresPressure: false, priority: 28,
    desc: "Makes food from water using power. No crew, so it runs when colonists are short; less efficient than Hydroponics.",
  },
  atomic: {
    id: "atomic", name: "Atomic Printer", glyph: "ATM",
    foot: [2, 2], h: 24, color: "#3a3850",
    cost: { power: 0 }, matCost: 120,
    staffing: 0, consumes: { power: 30 }, produces: {},
    printsLowest: { oxygen: 6, water: 8, food: 4, materials: 1 },
    requiresPressure: false, priority: 10,
    desc: "Uses a lot of power to make whichever of water, oxygen, food, or materials is lowest. No crew. The first thing cut in a brownout.",
  },
  roverbay: {
    id: "roverbay", name: "Rover Bay", glyph: "RVR",
    foot: [2, 2], h: 14, color: "#34414d",
    cost: { power: 0 }, matCost: 60,
    staffing: 0, consumes: { power: 2.5 }, produces: {},
    requiresPressure: false, priority: 25, door: 2,
    desc: "Builds one rover, a vehicle you drive to haul resources in bulk. Holds its build while unpowered.",
  },
  roboticsbay: {
    id: "roboticsbay", name: "Robotics Bay", glyph: "BOT",
    foot: [2, 2], h: 16, color: "#423d2f",
    cost: { power: 0 }, matCost: 90,
    staffing: 1, consumes: { power: 4 }, produces: {},
    requiresPressure: false, priority: 20, door: 2,
    desc: "Builds up to three mining robots that gather resources day and night. Needs one colonist.",
  },
  ptp: {
    id: "ptp", name: "Transport Pod", glyph: "PTP",
    foot: [2, 2], h: 30, color: "#5a4a6e",
    cost: { power: 0 }, matCost: 200,
    staffing: 0, consumes: { power: 8 }, produces: {},
    requiresPressure: false, priority: 30,
    desc: "Launches a crew to found a colony on another planet. Launching ends this run as an expansion.",
  },
};

/** Palette display order (doc §4.4 table order). */
export const ORDER: string[] = [
  "hub", "corridor", "hab", "solar", "battery",
  "extractor", "awg", "aquifer", "reclaimer",
  "electrolysis", "greenhouse", "medbay", "cistern", "o2tank", "deflector",
  "windturbine", "geothermal", "reactor", "printer", "bioprinter", "atomic",
  "roverbay", "roboticsbay", "ptp",
];
